version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-05h+j$kbep2)5qq5=k+#s1$7vwaz@$12bew5-!s6d(c(-3v5um
      - DATABASE_URL=sqlite:///new.sqlite3

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
